swagger: "2.0"
info:
  title: Game Analytics API
  description: API for uploading and querying game data from a CSV file.
  version: "1.0"
basePath: /api
schemes:
  - https
paths:
  /query:
    get:
      tags:
        - Query
      summary: Query the uploaded CSV data
      parameters:
        - name: filters
          in: query
          required: false
          type: string
      responses:
        200:
          description: Query results
        500:
          description: Internal server error
