swagger: "2.0"
info:
  title: Game Analytics API
  description: API for uploading and querying game data from a CSV file.
  version: "1.0"
basePath: /api
schemes:
  - http
paths:
  /upload:
    post:
      tags:
        - Upload
      summary: Upload a CSV file
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              csv_url:
                type: string
      responses:
        201:
          description: CSV data uploaded successfully
        400:
          description: CSV URL is required
        500:
          description: Internal server error
